import type { SchemaTable, SchemaColumn } from './introspect.js';

const STACKBY_TO_TS: Record<string, string> = {
  text: 'string',
  multilineText: 'string',
  number: 'number',
  currency: 'number',
  percent: 'number',
  checkbox: 'boolean',
  date: 'string',
  dateTime: 'string',
  duration: 'number',
  progress: 'number',
  rating: 'number',
  url: 'string',
  email: 'string',
  phone: 'string',
  barcode: 'string',
  formula: 'string | number | boolean',
  createdTime: 'string',
  lastModifiedTime: 'string',
  autoNumber: 'number',
  button: 'null',
  collaborator: 'CollaboratorValue',
  multiCollaborator: 'CollaboratorValue[]',
  multipleAttachment: 'AttachmentValue[]',
  link: 'string[]',
  lookup: 'unknown',
  rollup: 'number | null',
  count: 'number',
};

function sanitizeIdentifier(name: string): string {
  const s = name.replace(/[^a-zA-Z0-9_]/g, '_');
  return /^[^a-zA-Z_]/.test(s) ? `_${s}` : s;
}

function pascalCase(name: string): string {
  return name
    .split(/[\s_\-&/]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function getSelectTypeName(col: SchemaColumn, tableName: string): string {
  const choices = (col.options?.['choices'] ?? []) as Array<{ name: string }>;
  if (choices.length === 0) return 'string';
  return `${pascalCase(tableName)}${pascalCase(col.name)}`;
}

function generateColumnType(col: SchemaColumn, tableName: string): string {
  if (col.type === 'select') return getSelectTypeName(col, tableName);
  if (col.type === 'multiSelect') return `Array<${getSelectTypeName(col, tableName)}>`;
  return STACKBY_TO_TS[col.type] ?? 'unknown';
}

function generateEnumDeclaration(col: SchemaColumn, tableName: string): string | null {
  if (col.type !== 'select' && col.type !== 'multiSelect') return null;
  const choices = (col.options?.['choices'] ?? []) as Array<{ name: string }>;
  if (choices.length === 0) return null;
  const typeName = `${pascalCase(tableName)}${pascalCase(col.name)}`;
  const members = choices.map((c) => `  | ${JSON.stringify(c.name)}`).join('\n');
  return `export type ${typeName} =\n${members};`;
}

function generateTableInterface(table: SchemaTable): string {
  const lines: string[] = [];
  for (const col of table.columns) {
    const tsType = generateColumnType(col, table.name);
    const ro = col.readOnly ? 'readonly ' : '';
    const nullable = col.readOnly || col.type === 'button' ? ' | null' : '';
    lines.push(`  ${ro}${sanitizeIdentifier(col.name)}: ${tsType}${nullable};`);
  }
  return `export interface ${pascalCase(table.name)}Row {\n${lines.join('\n')}\n}`;
}

export function generateTypes(tables: SchemaTable[]): string {
  const parts: string[] = [
    '// AUTO-GENERATED by Stackby Studio Schema Service — do not edit manually',
    '',
    'export interface CollaboratorValue {',
    '  id: string;',
    '  email: string;',
    '  name?: string;',
    '}',
    '',
    'export interface AttachmentValue {',
    '  id: string;',
    '  url?: string;',
    '  filename?: string;',
    '  type?: string;',
    '  size?: number;',
    '}',
    '',
  ];

  for (const table of tables) {
    for (const col of table.columns) {
      const decl = generateEnumDeclaration(col, table.name);
      if (decl) {
        parts.push(decl);
        parts.push('');
      }
    }
  }

  for (const table of tables) {
    parts.push(generateTableInterface(table));
    parts.push('');
  }

  return parts.join('\n');
}
