import type { DesignTokens } from '@stackby/schema-types';

function kebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

/**
 * Generate a tokens.css file with CSS custom properties.
 * Every value is concrete — no var() references, no CSS preprocessing required.
 */
export function generateTokensCss(tokens: DesignTokens, prefix = '--'): string {
  const lines: string[] = [
    '/* Generated by Stackby Studio Design Service — do not edit manually */',
    ':root {',
  ];

  if (tokens.colors) {
    lines.push('  /* Colors */');
    for (const [key, value] of Object.entries(tokens.colors)) {
      if (typeof value === 'string') {
        lines.push(`  ${prefix}color-${kebab(key)}: ${value};`);
      }
    }
  }

  if (tokens.typography) {
    lines.push('  /* Typography */');
    const typo = tokens.typography;
    if (typeof typo.fontFamily === 'string') {
      lines.push(`  ${prefix}font-family: ${typo.fontFamily};`);
    }
    if (typo.fontSize) {
      for (const [key, value] of Object.entries(typo.fontSize)) {
        if (typeof value === 'string') lines.push(`  ${prefix}font-size-${kebab(key)}: ${value};`);
      }
    }
    if (typo.fontWeight) {
      for (const [key, value] of Object.entries(typo.fontWeight)) {
        if (value !== undefined) lines.push(`  ${prefix}font-weight-${kebab(key)}: ${value};`);
      }
    }
  }

  if (tokens.spacing) {
    lines.push('  /* Spacing */');
    for (const [key, value] of Object.entries(tokens.spacing)) {
      if (typeof value === 'string') lines.push(`  ${prefix}spacing-${key}: ${value};`);
    }
  }

  if (tokens.radii) {
    lines.push('  /* Border Radius */');
    for (const [key, value] of Object.entries(tokens.radii)) {
      if (typeof value === 'string') lines.push(`  ${prefix}radius-${kebab(key)}: ${value};`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}
