import type { DesignTokens } from '@stackby/schema-types';

function kebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

/**
 * Generate a tailwind.preset.js that references CSS custom properties.
 * Generated artifacts import this: `import preset from './tailwind.preset.js'`
 */
export function generateTailwindPreset(tokens: DesignTokens): string {
  const colors: Record<string, string> = {};
  if (tokens.colors) {
    for (const [key, value] of Object.entries(tokens.colors)) {
      if (typeof value === 'string') {
        colors[kebab(key)] = `var(--color-${kebab(key)})`;
      }
    }
  }

  const fontFamilyStr = typeof tokens.typography?.fontFamily === 'string'
    ? tokens.typography.fontFamily.split(',').map((f: string) => f.trim().replace(/^['"]|['"]$/g, ''))
    : ['system-ui', 'sans-serif'];

  const fontSize: Record<string, string> = {};
  if (tokens.typography?.fontSize) {
    for (const [key, value] of Object.entries(tokens.typography.fontSize)) {
      if (typeof value === 'string') fontSize[key] = value;
    }
  }

  const borderRadius: Record<string, string> = {};
  if (tokens.radii) {
    for (const [key, value] of Object.entries(tokens.radii)) {
      if (typeof value === 'string') borderRadius[key] = `var(--radius-${kebab(key)})`;
    }
  }

  const spacing: Record<string, string> = {};
  if (tokens.spacing) {
    for (const [key, value] of Object.entries(tokens.spacing)) {
      if (typeof value === 'string') spacing[key] = value;
    }
  }

  const colorsStr = JSON.stringify(colors, null, 6).replace(/"/g, "'");
  const fontFamilyArr = JSON.stringify(fontFamilyStr, null, 6);
  const fontSizeStr = JSON.stringify(fontSize, null, 6).replace(/"/g, "'");
  const borderRadiusStr = JSON.stringify(borderRadius, null, 6).replace(/"/g, "'");
  const spacingStr = JSON.stringify(spacing, null, 6).replace(/"/g, "'");

  return `/** Generated by Stackby Studio Design Service — do not edit manually */
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${colorsStr},
      fontFamily: {
        sans: ${fontFamilyArr},
      },
      fontSize: ${fontSizeStr},
      borderRadius: ${borderRadiusStr},
      spacing: ${spacingStr},
    },
  },
};
`;
}
