export const SPANS = {
  RUN: 'studio.run',
  INTENT_ANALYZE: 'studio.intent_analyze',
  SCHEMA_ANALYZE: 'studio.schema_analyze',
  CLARIFY: 'studio.clarify',
  PLAN: 'studio.plan',
  PLAN_REVIEW: 'studio.plan_review',
  DESIGN: 'studio.design',
  CODEGEN: 'studio.codegen',
  CODEGEN_FILE: 'studio.codegen.file',
  BUILD: 'studio.build',
  BUILD_TYPECHECK: 'studio.build.typecheck',
  BUILD_LINT: 'studio.build.lint',
  BUILD_BUNDLE: 'studio.build.bundle',
  VERIFY: 'studio.verify',
  FIX: 'studio.fix',
  PUBLISH: 'studio.publish',
  LLM_CALL: 'studio.llm_call',
  GATEWAY_READ: 'studio.gateway.read',
  GATEWAY_MUTATE: 'studio.gateway.mutate',
} as const;

export type SpanName = typeof SPANS[keyof typeof SPANS];

export const ATTRS = {
  RUN_ID: 'studio.run_id',
  PROJECT_ID: 'studio.project_id',
  WORKSPACE_ID: 'studio.workspace_id',
  ARTIFACT_TYPE: 'studio.artifact_type',
  STACK_ID: 'studio.stack_id',
  MODEL_ID: 'studio.model_id',
  MODEL_TIER: 'studio.model_tier',
  TOKENS_IN: 'studio.tokens_in',
  TOKENS_OUT: 'studio.tokens_out',
  CACHE_READ_TOKENS: 'studio.cache_read_tokens',
  COST_USD: 'studio.cost_usd',
  CREDIT_COST: 'studio.credit_cost',
  BUILD_SUCCESS: 'studio.build_success',
  ERRORS_COUNT: 'studio.errors_count',
  FIX_CYCLE: 'studio.fix_cycle',
  PROMPT_VERSION: 'studio.prompt_version',
  PLAN_STEP_COUNT: 'studio.plan_step_count',
  FILES_COUNT: 'studio.files_count',
  ELEMENT_COUNT: 'studio.element_count',
  VISIBILITY: 'studio.visibility',
  BINDING_COUNT: 'studio.binding_count',
} as const;
